// arm7_jit.cpp - ARM7DI -> PowerPC recompiler for the AICA sound CPU (Wii).
//
// PHASE 1 CONTRACT: behave exactly like the cached interpreter (arm7_cached.cpp,
// whose label bodies are generated by gen_arm7_cached.py): same results, same
// tick charges, same slice exits, same FIQ sample points, same writes to
// reg[15] and reg[R_COUT]. The speed comes from removing per-uop decode and
// dispatch, not from changing semantics, so any sound difference between
// arm7_jit on and off is a JIT bug rather than a timing change.
//
// Memory: no buffers of its own. It borrows the cached interpreter's ARM7_CACHE
// (as PPC code) and ARM7_ENTRYPOINTS (as the block table). arm_Reset() latches
// ONE engine and flushes both, so they never use that memory at the same time.
//
// Runtime layout while arm_jit_run() executes (callee-saved, pinned):
//   r31 = &arm_Reg[0]   r30 = budget (CycleCount - clockTicks)
//   r29 = arm_aica_ram  r28 = &N_FLAG (base for the flag bytes)
//   r27 = memory address, r26 = rn+-offset, r25 = value to store: they survive
//         the slow-path C calls.
// Blocks never return: they leave through the dispatch stub (FIQ check, budget
// check, next block) or the exit_now stub (mid-block budget exit, no FIQ check).
//
// Levels (arm7_jit preset, latched at arm_Reset):
//   1  every block exit goes through the C dispatcher
//   2  + static exits (B/BL, block cap) patched into direct branches
//   3  + the dispatch stub does FIQ/budget/table lookup in emitted code and
//        only calls C when one of them says so, and return-shaped dynamic
//        exits (MOV pc,Rm / SUBS pc,lr,#n / LDR pc,[Rn,#n] / LDM ..pc) get a
//        per-site cache of their last target. All three keep DISPATCH()
//        semantics: FIQ sample, budget check, then the block.
//   4  + LDM/STM inline when every word is in ARAM (push/pop), C otherwise.
//   5  + one `ble` per instruction for the budget test (ticks charged with
//        `addic.` at the end of the previous one), and EQ/NE/MI/PL right after
//        an N/Z-setting instruction compare its result instead of the flag byte.

#include "arm7.h"
#include "arm_mem.h"
#include "arm7_jit.h"

#if HOST_OS == OS_WII

// config.h poisons BIG_ENDIAN/LITTLE_ENDIAN; libogc defines them (as arm_aica.cpp).
#ifdef BIG_ENDIAN
#  undef BIG_ENDIAN
#endif
#ifdef LITTLE_ENDIAN
#  undef LITTLE_ENDIAN
#endif
#include <ogc/lwp_watchdog.h>   // gettime(): census timers only

extern "C" int get_arm7_jit_preset();   // wii/main.cpp

// ── Emitter and SH4-driver helpers (C++ linkage) ────────────────────────────
void* emit_GetCCPtr();                  // dc/sh4/rec_v2/driver.cpp
#include "emitter/PPCEmit/ppc_emitter.h"
#ifdef ppc_li
#  undef ppc_li                         // macro is 16-bit only; use the driver's
#endif
void ppc_li(u32 D, u32 imm);            // wii/dc/sh4/rec_v2/wii_driver.cpp
void ppc_call(void* funct);
void ppc_jump(void* funct);
u32  ppc_addr_high(u32 rD, void* ptr);
void make_address_range_executable(void* addr, u32 size);
extern u32* emit_ptr;                   // driver.cpp: redirects ppc_emit output

// ── ARM7 core state (arm7.cpp / arm_mem.cpp) ─────────────────────────────────
typedef union { u32 I; } reg_pair;
extern reg_pair arm_Reg[47];
extern u32  arm_ArmNextPC;
extern bool N_FLAG, Z_FLAG, C_FLAG, V_FLAG;
extern bool armFiqEnable;
extern int  armMode;
extern u8*  arm_aica_ram;

#define R_COUT 45

void CPUSwitchMode(int mode, bool saveState, bool breakLoop);
void CPUUpdateCPSR();
void CPUUpdateFlags(bool breakLoop);
void CPUSoftwareInterrupt(int comment);
void CPUUndefinedException();
void CPUFiq();

// arm7_cached.cpp
void arm_cached_stm(u32 opcode, int& clockTicks);
void arm_cached_ldm(u32 opcode, int& clockTicks, bool hasPC);
void arm7_cached_borrow_buffers(u8** code, u32* code_bytes, void*** entries, u32* entry_count);

// ── PPC register roles ───────────────────────────────────────────────────────
enum
{
	R_VAL  = 25,   // STR value
	R_WB   = 26,   // rn +- offset
	R_ADDR = 27,   // memory address / result kept across a call
	R_FLG  = 28,
	R_RAM  = 29,
	R_BUD  = 30,
	R_REG  = 31,
};

static const u32 MAX_BLOCK_INSNS = 128;     // == MAX_BLOCK_UOPS in arm7_cached.cpp
static const u32 COLD_FLUSH_INSNS = 16;     // keeps every bc displacement tiny
static const u32 MAX_BLOCK_WORDS = 16384;   // free space demanded before compiling

// ── JIT state ────────────────────────────────────────────────────────────────
static u32*   s_code_base;
static u32    s_code_words;
static u32*   s_code_blocks;       // first word after the stubs
static u32*   s_code_cur;
static void** s_entries;
static u32    s_entry_mask;

static void*  s_stub_entry;
static void*  s_stub_dispatch;
static void*  s_stub_exit_now;
static void*  s_stub_exit;
static void*  s_stub_link;
static void*  s_stub_icmiss;
static bool   s_link;               // arm7_jit >= 2: static exits patched into direct branches
static bool   s_retcache;           // arm7_jit >= 3: emitted dispatch + per-site return cache
static bool   s_inline_blk;         // arm7_jit >= 4: LDM/STM inline for ARAM addresses
static u32    s_slices;             // arm_jit_run calls: the clock for return-cache demotion

// Census (printed with the jit_ccalls probe, latched at reset so the emitted
// counters and the C ones always describe the same blocks). Costs nothing
// when off: emitted counters are simply not generated.
enum
{
	ARMC_SLICE, ARMC_DISPATCH, ARMC_DISPATCH_C, ARMC_FIQ,
	ARMC_COMPILE, ARMC_LINK_C, ARMC_DYN, ARMC_IC_SITE, ARMC_IC_MISS,
	ARMC_IC_PATCH, ARMC_IC_DEMOTE, ARMC_RD_SLOW, ARMC_WR_SLOW, ARMC_LDM,
	ARMC_STM, ARMC_BLK_INLINE, ARMC_OTHER,
	// dynamic exits by shape (e_dyn_exit)
	ARMC_DYN_MOV, ARMC_DYN_SUB, ARMC_DYN_DP_OTHER, ARMC_DYN_LDR_IMM,
	ARMC_DYN_LDR_LIT, ARMC_DYN_LDR_REG, ARMC_DYN_LDM, ARMC_DYN_SWI,
	ARMC_COUNT
};
extern "C" int g_jit_ccalls_preset;   // dc/sh4/rec_v2/shil.cpp
static bool   s_census;
static u32    s_cnt[ARMC_COUNT];
#define ARMC(i) do { if (s_census) s_cnt[i]++; } while (0)

// Census wall time inside the C side, to set against arm:% on the stats line.
// Only the outermost timer on the stack counts (jit_link_c -> jit_dispatch_c).
enum { ARMT_DISPATCH, ARMT_RD, ARMT_WR, ARMT_BLOCK, ARMT_OTHER, ARMT_COUNT };
static u64    s_tcost[ARMT_COUNT];
static bool   s_timing;
struct CensusTimer
{
	u32 k; u64 t0; bool on;
	explicit CensusTimer(u32 kind) : k(kind), t0(0), on(s_census && !s_timing)
	{
		if (on) { s_timing = true; t0 = gettime(); }
	}
	~CensusTimer()
	{
		if (on) { s_tcost[k] += gettime() - t0; s_timing = false; }
	}
};

// Block-table entries written since the last flush. The table is 2 MB and the
// self-test alone resets ~45 times, so a flush clears only this range, unless
// the cached interpreter may have filled the table since (full clear then).
static u32    s_dirty_lo = 0xFFFFFFFF;
static u32    s_dirty_hi;
static bool   s_table_foreign = true;

static bool   s_setup_done;
static bool   s_setup_ok;
static bool   s_active;
static bool   s_failed;             // self-test failed: never latch the JIT again
static bool   s_selftest_started;
static bool   s_announced;
static u32    s_blocks;
static u32    s_flushes;

// reg[15] materialized in THIS instruction (value known at compile time)?
static bool   s_pc15_known;
static u32    s_pc15_val;

// ── Small emit helpers ───────────────────────────────────────────────────────
static inline bool in_s16(s32 v) { return v >= -32768 && v <= 32767; }

static inline void e_rlwinm(u32 a, u32 s, u32 sh, u32 mb, u32 me)
{
	ppc_rlwinmx(a, s, sh & 31, mb, me, 0);
}

// Level 5 ("lean"): an instruction's ticks are summed at compile time and
// charged once, with `addic.`, at its end (or before its exit branch). The
// resulting CR0 is the next instruction's budget test, so each instruction
// after the first needs only `ble` instead of `cmpwi / ble / addi`. Same
// budget at every exit point as the per-instruction form, so same timing.
static bool s_fold;                 // arm7_jit >= 5
static u32  s_ticks;                // ticks of the current instruction not yet charged
static bool s_cr0_budget;           // CR0 holds the sign of the budget right now

// N/Z forwarding (level 5): the previous instruction was an unconditional N/Z
// producer whose result is still in this PPC register (0 = none), so an
// EQ/NE/MI/PL test compares it instead of reloading the flag byte just stored.
static u32  s_nz_fwd_next;
static bool s_nz_in_r7;             // this instruction set N/Z from r7

static inline void e_ticks(u32 n)
{
	if (s_fold)
		s_ticks += n;
	else
		ppc_addi(R_BUD, R_BUD, (u32)(-(s32)n));
}

// Charge the pending ticks (level 5). set_cr0: leave CR0 = budget sign for the
// next instruction's `ble`; exits don't need it (the next block tests itself).
static void e_charge(bool set_cr0)
{
	if (!s_fold)
		return;
	if (s_ticks)
		ppc_addic(R_BUD, R_BUD, (u32)(-(s32)s_ticks), set_cr0 ? 1 : 0);
	else if (set_cr0)
		ppc_cmpi(0, R_BUD, 0, 0);
	s_ticks = 0;
}

static void e_load_byte(u32 dst, void* p)
{
	s32 d = (s32)((u8*)p - (u8*)&N_FLAG);
	if (in_s16(d))
		ppc_lbz(dst, R_FLG, (u32)d);
	else
	{
		u32 lo = ppc_addr_high(dst, p);
		ppc_lbz(dst, dst, lo);
	}
}

static void e_store_byte(u32 src, void* p)
{
	s32 d = (s32)((u8*)p - (u8*)&N_FLAG);
	if (in_s16(d))
		ppc_stb(src, R_FLG, (u32)d);
	else
	{
		u32 lo = ppc_addr_high(11, p);
		ppc_stb(src, 11, lo);
	}
}

static void e_load_reg(u32 dst, u32 r)
{
	if (r == 15 && s_pc15_known)
		ppc_li(dst, s_pc15_val);
	else
		ppc_lwz(dst, R_REG, r * 4);
}

static void e_store_reg(u32 src, u32 r)
{
	ppc_stw(src, R_REG, r * 4);
	if (r == 15)
		s_pc15_known = false;
}

// The cached interpreter's SET_PC_READ / "_pcr" shift uop: write reg[15] to
// memory (later instructions may read it back) and remember the constant.
static void e_set_pc15(u32 val)
{
	ppc_li(12, val);
	ppc_stw(12, R_REG, 15 * 4);
	s_pc15_known = true;
	s_pc15_val = val;
}

static void e_call(void* f)
{
	ppc_call(f);
	s_pc15_known = false;   // conservative: helpers may write reg[15]
}

// Census counter bump (r11/r12, flags untouched). Emitted only with the census on.
static const u32 COUNT_WORDS = 4;
static void e_count(u32 idx)
{
	if (!s_census)
		return;
	u32* start = emit_ptr;
	u32 lo = ppc_addr_high(12, &s_cnt[idx]);
	ppc_lwz(11, 12, lo);
	ppc_addi(11, 11, 1);
	ppc_stw(11, 12, lo);
	verify(emit_ptr - start == (s32)COUNT_WORDS);
}

static u32* e_bc_placeholder(u32 bo, u32 bi)
{
	u32* site = emit_ptr;
	ppc_bcx(bo, bi, 0, 0, 0);
	return site;
}

static void patch_bc(u32* site, u32* target)
{
	s32 d = (s32)((u8*)target - (u8*)site);
	verify(in_s16(d));
	*site |= (u32)d & 0xFFFC;
}

static void e_bc_to(u32 bo, u32 bi, u32* target)
{
	s32 d = (s32)((u8*)target - (u8*)emit_ptr);
	verify(in_s16(d));
	ppc_bcx(bo, bi, (u32)(d >> 2), 0, 0);
}

// N and Z from the result in r7 (r9 temp).
static void e_flags_nz(u32 res)
{
	e_rlwinm(9, res, 1, 31, 31);
	e_store_byte(9, &N_FLAG);
	ppc_cntlzwx(9, res, 0);
	e_rlwinm(9, 9, 27, 31, 31);
	e_store_byte(9, &Z_FLAG);
	s_nz_in_r7 = (res == 7);
}

// C from XER[CA] (must run right after the flag-producing add/sub).
static void e_flag_c_from_ca()
{
	ppc_li(9, 0);
	ppc_addzex(9, 9, 0, 0);
	e_store_byte(9, &C_FLAG);
}

// XER[CA] = C_FLAG, for adde/subfe.
static void e_ca_from_c()
{
	e_load_byte(8, &C_FLAG);
	ppc_addic(8, 8, (u32)-1, 0);
}

// ── Slow-path memory helpers ─────────────────────────────────────────────────
static u32  jit_rd32(u32 a)        { ARMC(ARMC_RD_SLOW); CensusTimer t(ARMT_RD); return arm_ReadMem32(a); }
static u32  jit_rd8(u32 a)         { ARMC(ARMC_RD_SLOW); CensusTimer t(ARMT_RD); return arm_ReadMem8(a); }
static void jit_wr32(u32 a, u32 v) { ARMC(ARMC_WR_SLOW); CensusTimer t(ARMT_WR); arm_WriteMem32(a, v); }
static void jit_wr8(u32 a, u32 v)  { ARMC(ARMC_WR_SLOW); CensusTimer t(ARMT_WR); arm_WriteMem8(a, (u8)v); }

// LDM/STM helpers (defined below), also reached from the CK_BLOCK cold stub.
static int jit_stm(u32 op);
static int jit_ldm_nopc(u32 op);
static int jit_ldm_pc(u32 op);

// ── Cold stub queue ──────────────────────────────────────────────────────────
// Out-of-line code (budget exits, failed conditions, slow memory paths) is
// queued and emitted every COLD_FLUSH_INSNS instructions behind one `b over`,
// so the hot path stays branch-free and every conditional branch stays short.
enum ColdKind { CK_BUDGET, CK_FAIL, CK_FAIL_LAST, CK_RD, CK_WR, CK_BLOCK };

struct ColdStub
{
	u32  kind;
	u32  size;     // CK_RD / CK_WR: 1 or 4. CK_BLOCK: 0 stm, 1 ldm, 2 ldm with pc
	u32* site;     // conditional branch to patch
	u32  pc;       // ARM pc handed to exit_now / dispatch (CK_BLOCK: the opcode)
	u32* back;     // where to resume (CK_FAIL: next instruction; CK_RD/WR/BLOCK: join)
};

static ColdStub s_cold[256];
static u32      s_cold_n;
static u32*     s_pending_back[16];
static u32      s_pending_n;

static void cold_push(u32 kind, u32* site, u32 pc, u32* back, u32 size)
{
	verify(s_cold_n < sizeof(s_cold) / sizeof(s_cold[0]));
	ColdStub& c = s_cold[s_cold_n++];
	c.kind = kind; c.site = site; c.pc = pc; c.back = back; c.size = size;
}

// Leave the block for a pc known at compile time (DISPATCH_PC semantics).
static void e_link(u32 target)
{
	e_charge(false);
	if (!s_link)
	{
		ppc_li(3, target);
		ppc_jump(s_stub_dispatch);
		return;
	}

	// Target already compiled: branch straight to its link entry.
	void* code = s_entries[(target >> 2) & s_entry_mask];
	if (code && ((u32*)code)[-1] == target)
	{
		ppc_jump((u32*)code - ((u32*)code)[-2]);
		return;
	}

	// Fixed 3-word shape: jit_link_c patches the first word.
	ppc_addis(3, 0, target >> 16);
	ppc_ori(3, 3, target & 0xFFFF);
	ppc_call(s_stub_link);
}

// Return-cache site bookkeeping (arm7_jit >= 3, see jit_icmiss_c).
static const u32 IC_SITE_WORDS    = 7;
static const u32 IC_UNRESOLVED    = 0x48000004;   // w3 `b +4`: nothing cached yet
static const u32 IC_REPROBE       = 64;           // misses tolerated before re-patching
static const u32 IC_DEMOTE_SLICES = 1024;         // re-patch due again this soon -> give up

// Leave the block for a pc known only at run time (r3). With the return cache,
// a cacheable exit is emitted as
//     w0 addis r4,r3,-pc@h        r4 = r3 - cached pc (high half)
//     w1 cmplwi r4,pc@l           ...low half: equal <=> same target
//     w2 bne   w4
//     w3 b     link entry         (b w4 until the first patch)
//     w4 bl    icmiss_stub        LR = w5
//     w5 .long misses left before the next re-patch (0 = patch on the next miss)
//     w6 .long s_slices at the last patch
// A hit lands on the target's link entry (FIQ sample), then its instruction 0
// (budget check): the same DISPATCH() the dispatcher would have done.
// kind: ARMC_DYN_* shape. Cached: returns and calls through a register or a
// literal (one target per site in practice); not: jump tables (register-offset
// LDR, pc arithmetic) and exceptions.
static void e_dyn_exit(u32 kind)
{
	bool cacheable = kind == ARMC_DYN_MOV || kind == ARMC_DYN_SUB || kind == ARMC_DYN_LDR_IMM ||
	                 kind == ARMC_DYN_LDR_LIT || kind == ARMC_DYN_LDM;
	e_charge(false);                           // r3 untouched
	e_count(ARMC_DYN);
	e_count(kind);
	if (!s_retcache || !cacheable)
	{
		ppc_jump(s_stub_dispatch);
		return;
	}

	e_count(ARMC_IC_SITE);                     // must stay right before w0 (demotion)
	u32* site = emit_ptr;
	ppc_addis(4, 3, 0);
	ppc_cmpli(0, 4, 0, 0);
	ppc_bcx(BO_FALSE, BI_CR0_EQ, 2, 0, 0);
	ppc_bx(1, 0, 0);
	ppc_call(s_stub_icmiss);
	ppc_emit(0);
	ppc_emit(0);
	verify(emit_ptr - site == (s32)IC_SITE_WORDS && site[3] == IC_UNRESOLVED);
}

static void flush_cold()
{
	if (!s_cold_n)
		return;

	u32* skip = emit_ptr;
	ppc_bx(0, 0, 0);                       // b over (patched below)

	for (u32 i = 0; i < s_cold_n; i++)
	{
		ColdStub& c = s_cold[i];
		patch_bc(c.site, emit_ptr);

		switch (c.kind)
		{
		case CK_BUDGET:                    // ADVANCE() ran out: no FIQ sample
			ppc_li(3, c.pc);
			ppc_jump(s_stub_exit_now);
			break;

		case CK_FAIL_LAST:                 // COND_FAIL on a block-ending insn
			if (s_fold)
				ppc_addi(R_BUD, R_BUD, (u32)-6);   // the skipped body charged nothing
			e_link(c.pc);
			break;

		case CK_FAIL:                      // COND_FAIL mid-block: DISPATCH() samples FIQ
			if (s_fold)
			{
				// Charge the failed instruction, sample FIQ, and resume with CR0
				// holding the budget sign for the next instruction's `ble`.
				ppc_addi(R_BUD, R_BUD, (u32)-6);
				e_load_byte(3, &armFiqEnable);
				e_load_byte(4, &e68k_out);
				ppc_andx(3, 3, 4, 1);
				u32* fiq = e_bc_placeholder(BO_FALSE, BI_CR0_EQ);
				ppc_cmpi(0, R_BUD, 0, 0);
				if (c.back)
					e_bc_to(BO_ALWAYS, BI_CR0_EQ, c.back);
				else
				{
					verify(s_pending_n < sizeof(s_pending_back) / sizeof(s_pending_back[0]));
					s_pending_back[s_pending_n++] = e_bc_placeholder(BO_ALWAYS, BI_CR0_EQ);
				}
				patch_bc(fiq, emit_ptr);
				ppc_li(3, c.pc);
				ppc_jump(s_stub_dispatch);
				break;
			}
			e_load_byte(3, &armFiqEnable);
			e_load_byte(4, &e68k_out);
			ppc_andx(3, 3, 4, 1);
			if (c.back)
				e_bc_to(BO_TRUE, BI_CR0_EQ, c.back);
			else
			{
				verify(s_pending_n < sizeof(s_pending_back) / sizeof(s_pending_back[0]));
				s_pending_back[s_pending_n++] = e_bc_placeholder(BO_TRUE, BI_CR0_EQ);
			}
			ppc_li(3, c.pc);
			ppc_jump(s_stub_dispatch);
			break;

		case CK_RD:
			ppc_mr(3, R_ADDR);
			ppc_call(c.size == 1 ? (void*)&jit_rd8 : (void*)&jit_rd32);
			if (c.size == 1)
				ppc_andi(3, 3, 0xFF);
			ppc_jump(c.back);
			break;

		case CK_WR:
			ppc_mr(3, R_ADDR);
			if (c.size == 1)
				ppc_andi(4, R_VAL, 0xFF);
			else
				ppc_mr(4, R_VAL);
			ppc_call(c.size == 1 ? (void*)&jit_wr8 : (void*)&jit_wr32);
			ppc_jump(c.back);
			break;

		case CK_BLOCK:                     // LDM/STM outside ARAM: the C helper
			ppc_li(3, c.pc);
			ppc_call(c.size == 0 ? (void*)&jit_stm :
			         c.size == 1 ? (void*)&jit_ldm_nopc : (void*)&jit_ldm_pc);
			if (c.size == 2)
			{
				u32 lo = ppc_addr_high(3, &arm_ArmNextPC);
				ppc_lwz(3, 3, lo);
			}
			ppc_jump(c.back);               // ticks are charged after the join
			break;
		}
	}

	*skip |= (u32)((u8*)emit_ptr - (u8*)skip) & 0x03FFFFFC;
	s_cold_n = 0;
}

// ── Helpers mirroring the cached labels that stay in C ───────────────────────
static int jit_stm(u32 op)      { ARMC(ARMC_STM); CensusTimer c(ARMT_BLOCK); int t = 0; arm_cached_stm(op, t);        return t; }
static int jit_ldm_nopc(u32 op) { ARMC(ARMC_LDM); CensusTimer c(ARMT_BLOCK); int t = 0; arm_cached_ldm(op, t, false); return t; }
static int jit_ldm_pc(u32 op)   { ARMC(ARMC_LDM); CensusTimer c(ARMT_BLOCK); int t = 0; arm_cached_ldm(op, t, true);  return t; }

static void jit_swp(u32 op)      // lbl_swp / lbl_swpb
{
	ARMC(ARMC_OTHER);
	CensusTimer c(ARMT_OTHER);
	u32 rd = (op >> 12) & 0xF, rn = (op >> 16) & 0xF, rm = op & 0xF;
	u32 address = arm_Reg[rn].I;
	if (op & 0x00400000)
	{
		u32 temp = arm_ReadMem8(address);
		arm_WriteMem8(address, arm_Reg[rm].I & 0xFF);
		arm_Reg[rd].I = temp & 0xFF;
	}
	else
	{
		u32 temp = arm_ReadMem32(address);
		arm_WriteMem32(address, arm_Reg[rm].I);
		arm_Reg[rd].I = temp;
	}
}

static void jit_msr_cpsr(u32 opcode)   // lbl_msr_cpsr
{
	ARMC(ARMC_OTHER);
	CensusTimer c(ARMT_OTHER);
	CPUUpdateCPSR();
	u32 value;
	if (opcode & 0x02000000)
	{
		value = opcode & 0xFF;
		int shift = (opcode & 0xF00) >> 7;
		if (shift) value = ((value << (32 - shift)) | (value >> shift));
	}
	else
		value = arm_Reg[opcode & 15].I;
	u32 newValue = arm_Reg[16].I;
	if (armMode > 0x10)
	{
		if (opcode & 0x00010000) newValue = (newValue & 0xFFFFFF00) | (value & 0x000000FF);
		if (opcode & 0x00020000) newValue = (newValue & 0xFFFF00FF) | (value & 0x0000FF00);
		if (opcode & 0x00040000) newValue = (newValue & 0xFF00FFFF) | (value & 0x00FF0000);
	}
	if (opcode & 0x00080000) newValue = (newValue & 0x00FFFFFF) | (value & 0xFF000000);
	newValue |= 0x10;
	CPUSwitchMode(newValue & 0x1f, false, true);
	arm_Reg[16].I = newValue;
	CPUUpdateFlags(true);
}

static void jit_msr_spsr(u32 opcode)   // lbl_msr_spsr
{
	ARMC(ARMC_OTHER);
	CensusTimer c(ARMT_OTHER);
	if (armMode > 0x10 && armMode < 0x1f)
	{
		u32 value;
		if (opcode & 0x02000000)
		{
			value = opcode & 0xFF;
			int shift = (opcode & 0xF00) >> 7;
			if (shift) value = ((value << (32 - shift)) | (value >> shift));
		}
		else
			value = arm_Reg[opcode & 15].I;
		if (opcode & 0x00010000) arm_Reg[17].I = (arm_Reg[17].I & 0xFFFFFF00) | (value & 0x000000FF);
		if (opcode & 0x00020000) arm_Reg[17].I = (arm_Reg[17].I & 0xFFFF00FF) | (value & 0x0000FF00);
		if (opcode & 0x00040000) arm_Reg[17].I = (arm_Reg[17].I & 0xFF00FFFF) | (value & 0x00FF0000);
		if (opcode & 0x00080000) arm_Reg[17].I = (arm_Reg[17].I & 0x00FFFFFF) | (value & 0xFF000000);
	}
}

static void jit_swi(u32 op)             // lbl_swi (after its +3 and SET_PC_READ)
{
	ARMC(ARMC_OTHER);
	CensusTimer c(ARMT_OTHER);
	CPUSoftwareInterrupt(op & 0x00FFFFFF);
}

static void jit_undefined(u32 op, u32 pc)   // lbl_undefined (after SET_PC_READ)
{
	ARMC(ARMC_OTHER);
	CensusTimer c(ARMT_OTHER);
	printf("Undefined ARM instruction (jit) %08x at %08x\n", op, pc);
	CPUUndefinedException();
}

static void jit_dp_switchmode()        // data-processing S with Rd == r15
{
	ARMC(ARMC_OTHER);
	CensusTimer c(ARMT_OTHER);
	CPUSwitchMode(arm_Reg[17].I & 0x1f, false, true);
}

// Register-specified shift (lbl_sh_/lbl_shc_ *r forms, copied verbatim from
// gen_arm7_cached.py shift_body): value returned, carry into reg[R_COUT] when
// kind bit 2 is set. Reads Rm and Rs from memory exactly like the uop does.
static u32 jit_shift_reg(u32 rm, u32 rs, u32 kind)
{
	ARMC(ARMC_OTHER);
	CensusTimer c(ARMT_OTHER);
	u32 v = arm_Reg[rm].I;
	u32 s = arm_Reg[rs].I & 0xFF;
	bool cw = (kind & 4) != 0;
	u32 value;

	switch (kind & 3)
	{
	case 0:   // LSL
		if (s)
		{
			if (s == 32)     { if (cw) arm_Reg[R_COUT].I = (v & 1) ? 1 : 0;                 value = 0; }
			else if (s < 32) { if (cw) arm_Reg[R_COUT].I = ((v >> (32 - s)) & 1) ? 1 : 0;   value = v << s; }
			else             { if (cw) arm_Reg[R_COUT].I = 0;                               value = 0; }
		}
		else
			value = v;
		break;

	case 1:   // LSR
		if (s)
		{
			if (s == 32)     { if (cw) arm_Reg[R_COUT].I = (v & 0x80000000) ? 1 : 0;        value = 0; }
			else if (s < 32) { if (cw) arm_Reg[R_COUT].I = ((v >> (s - 1)) & 1) ? 1 : 0;    value = v >> s; }
			else             { if (cw) arm_Reg[R_COUT].I = 0;                               value = 0; }
		}
		else
			value = v;
		break;

	case 2:   // ASR
		if (s < 32)
		{
			if (s) { if (cw) arm_Reg[R_COUT].I = (((s32)v >> (int)(s - 1)) & 1) ? 1 : 0; value = (u32)((s32)v >> (int)s); }
			else   { value = v; }
		}
		else if (v & 0x80000000) { if (cw) arm_Reg[R_COUT].I = 1; value = 0xFFFFFFFF; }
		else                     { if (cw) arm_Reg[R_COUT].I = 0; value = 0; }
		break;

	default:  // ROR
		if (s)
		{
			s &= 0x1f;
			if (s) { if (cw) arm_Reg[R_COUT].I = ((v >> (s - 1)) & 1) ? 1 : 0; value = (v << (32 - s)) | (v >> s); }
			else   { if (cw) arm_Reg[R_COUT].I = (v & 0x80000000) ? 1 : 0;     value = v; }
		}
		else
		{
			if (cw) arm_Reg[R_COUT].I = (v & 0x80000000) ? 1 : 0;
			value = v;
		}
		break;
	}
	return value;
}

// ── Dispatch (called from the dispatch stub) ─────────────────────────────────
static void* compile_block(u32 block_pc);

// Block layout (see compile_block): code[-1] = ARM pc, code[-2] = words from
// the link entry to code, code[-3] = ARM instructions, code[-4] = census count.
static void* jit_lookup(u32 pc)
{
	void* code = s_entries[(pc >> 2) & s_entry_mask];
	if (!code || ((u32*)code)[-1] != pc)
		code = compile_block(pc);
	return code;
}

// DISPATCH(): FIQ sample, budget check, then the block for pc.
static void* jit_dispatch_c(u32 pc, s32 budget)
{
	ARMC(ARMC_DISPATCH_C);
	CensusTimer c(ARMT_DISPATCH);
	if (armFiqEnable && e68k_out)
	{
		ARMC(ARMC_FIQ);
		arm_Reg[15].I = pc + 4;
		CPUFiq();
		pc = arm_ArmNextPC;
	}

	if (budget <= 0)
	{
		arm_ArmNextPC = pc;
		arm_Reg[15].I = pc + 4;
		return 0;
	}

	return jit_lookup(pc);
}

// Linked exits (arm7_jit >= 2). A static exit (B/BL target, failed condition on
// a block-ending instruction, block cap) is emitted as
//     lis r3,pc@h / ori r3,r3,pc@l / bl link_stub
// Its first run lands here with the same DISPATCH() semantics as above. Then,
// unless compiling flushed the cache (the site died with it), the lis word is
// overwritten with `b` to the target's link entry, which repeats DISPATCH()'s
// FIQ sample itself; instruction 0's own budget check does the rest.
static void* jit_link_c(u32 pc, s32 budget, u32* lr)
{
	ARMC(ARMC_LINK_C);
	CensusTimer c(ARMT_DISPATCH);
	if ((armFiqEnable && e68k_out) || budget <= 0)
		return jit_dispatch_c(pc, budget);

	u32 flushes = s_flushes;
	void* code = jit_lookup(pc);
	if (s_flushes == flushes)
	{
		u32* site = lr - 3;
		u32* link = (u32*)code - ((u32*)code)[-2];
		s32 d = (s32)((u8*)link - (u8*)site);
		*site = 0x48000000 | ((u32)d & 0x03FFFFFC);
		make_address_range_executable(site, 4);
	}
	return code;
}

// Return-cache miss with its countdown at 0 (the icmiss stub decrements it in
// emitted code otherwise and uses the plain dispatcher). lr = &w5 of the site.
// Normally: (re)point the site at this target, DISPATCH() semantics for the
// jump itself. A site due for re-patching again within IC_DEMOTE_SLICES of the
// last patch keeps missing at a high rate (a jump table, or a helper returning
// to two alternating callers), so it is turned into a plain `b dispatch`.
static void* jit_icmiss_c(u32 pc, s32 budget, u32* lr)
{
	CensusTimer c(ARMT_DISPATCH);
	if ((armFiqEnable && e68k_out) || budget <= 0)
		return jit_dispatch_c(pc, budget);      // countdown stays 0: retry next miss

	u32 flushes = s_flushes;
	void* code = jit_lookup(pc);
	if (s_flushes != flushes)
		return code;                            // the site was flushed with the cache

	u32* site = lr - 5;
	if (site[3] != IC_UNRESOLVED && s_slices - site[6] < IC_DEMOTE_SLICES)
	{
		// Over the site's own census counter when there is one, so a demoted
		// site stops counting as a cached one (s_census is per cache generation).
		u32* at = s_census ? site - COUNT_WORDS : site;
		if (s_census)
		{
			// The two targets it alternates between are return addresses:
			// the instruction before each is the BL that called the helper.
			u32 prev = ((0u - (site[0] & 0xFFFF)) & 0xFFFF) << 16 | (site[1] & 0xFFFF);
			printf("[ARMJIT] return cache: site demoted, targets %08x / %08x\n", prev, pc);
		}
		s32 d = (s32)((u8*)s_stub_dispatch - (u8*)at);
		*at = 0x48000000 | ((u32)d & 0x03FFFFFC);
		make_address_range_executable(at, 4);
		ARMC(ARMC_IC_DEMOTE);
		return code;
	}

	u32* link = (u32*)code - ((u32*)code)[-2];
	s32 d = (s32)((u8*)link - (u8*)&site[3]);
	site[0] = (site[0] & 0xFFFF0000) | ((0u - (pc >> 16)) & 0xFFFF);
	site[1] = (site[1] & 0xFFFF0000) | (pc & 0xFFFF);
	site[3] = 0x48000000 | ((u32)d & 0x03FFFFFC);
	site[5] = IC_REPROBE;
	site[6] = s_slices;
	make_address_range_executable(site, 4 * 4);
	ARMC(ARMC_IC_PATCH);
	return code;
}

// ── Stubs ────────────────────────────────────────────────────────────────────
static void emit_stubs()
{
	u32* saved_emit_ptr = emit_ptr;
	emit_ptr = s_code_base;

	// entry: void (s32 budget), C ABI
	s_stub_entry = emit_ptr;
	ppc_mflr(0);
	ppc_stwu(1, 1, (u32)-64);
	ppc_stw(0, 1, 68);
	for (u32 i = 0; i < 8; i++)
		ppc_stw(24 + i, 1, 32 + i * 4);
	ppc_mr(R_BUD, 3);
	ppc_li(R_REG, (u32)&arm_Reg[0]);
	ppc_li(R_FLG, (u32)&N_FLAG);
	{ u32 lo = ppc_addr_high(R_RAM, &arm_aica_ram); ppc_lwz(R_RAM, R_RAM, lo); }
	{ u32 lo = ppc_addr_high(3, &arm_ArmNextPC);    ppc_lwz(3, 3, lo); }

	// dispatch: r3 = pc
	s_stub_dispatch = emit_ptr;
	e_count(ARMC_DISPATCH);
	if (s_retcache)
	{
		// DISPATCH() in emitted code. Any of FIQ pending, budget spent or block
		// not compiled falls through to jit_dispatch_c, which redoes all three.
		u32 k = 0;
		while (k < 30 && (2u << k) <= s_entry_mask + 1)
			k++;                                   // table holds 2^k entries (k <= 30)
		u32 tbl = (u32)s_entries;
		u32 lo  = tbl & 0xFFFF;
		u32 hi  = (tbl - (u32)(s32)(s16)lo) >> 16;
		u32* miss[4];

		e_load_byte(4, &armFiqEnable);
		e_load_byte(5, &e68k_out);
		ppc_andx(4, 4, 5, 1);
		miss[0] = e_bc_placeholder(BO_FALSE, BI_CR0_EQ);
		ppc_cmpi(0, R_BUD, 0, 0);
		miss[1] = e_bc_placeholder(BO_FALSE, BI_CR0_GT);
		e_rlwinm(4, 3, 0, 30 - k, 29);             // ((pc >> 2) & mask) * 4
		ppc_addis(4, 4, hi);
		ppc_lwz(5, 4, lo);                         // code = s_entries[...]
		ppc_cmpli(0, 5, 0, 0);
		miss[2] = e_bc_placeholder(BO_TRUE, BI_CR0_EQ);
		ppc_lwz(6, 5, (u32)-4);                    // code[-1] == pc ?
		ppc_cmpl(0, 6, 3, 0);
		miss[3] = e_bc_placeholder(BO_FALSE, BI_CR0_EQ);
		ppc_mtctr(5);
		ppc_bctr();
		for (u32 i = 0; i < 4; i++)
			patch_bc(miss[i], emit_ptr);
	}
	ppc_mr(4, R_BUD);
	ppc_call((void*)&jit_dispatch_c);
	ppc_cmpli(0, 3, 0, 0);
	u32* to_exit = e_bc_placeholder(BO_TRUE, BI_CR0_EQ);
	ppc_mtctr(3);
	ppc_bctr();

	// exit_now: r3 = pc of the instruction that was not started
	s_stub_exit_now = emit_ptr;
	ppc_addi(4, 3, 4);
	ppc_stw(4, R_REG, 15 * 4);
	{ u32 lo = ppc_addr_high(4, &arm_ArmNextPC); ppc_stw(3, 4, lo); }

	// exit
	s_stub_exit = emit_ptr;
	patch_bc(to_exit, emit_ptr);
	for (u32 i = 0; i < 8; i++)
		ppc_lwz(24 + i, 1, 32 + i * 4);
	ppc_lwz(0, 1, 68);
	ppc_mtlr(0);
	ppc_addi(1, 1, 64);
	ppc_blr();

	// link: r3 = target pc, LR = just past the exit's `bl`
	s_stub_link = emit_ptr;
	ppc_mflr(5);
	ppc_mr(4, R_BUD);
	ppc_call((void*)&jit_link_c);
	ppc_cmpli(0, 3, 0, 0);
	e_bc_to(BO_TRUE, BI_CR0_EQ, (u32*)s_stub_exit);
	ppc_mtctr(3);
	ppc_bctr();

	// icmiss: r3 = pc, LR = &w5 of the return-cache site that missed
	s_stub_icmiss = emit_ptr;
	if (s_retcache)
	{
		e_count(ARMC_IC_MISS);
		ppc_mflr(5);
		ppc_lwz(6, 5, 0);
		ppc_cmpli(0, 6, 0, 0);
		u32* to_c = e_bc_placeholder(BO_TRUE, BI_CR0_EQ);
		ppc_addi(6, 6, (u32)-1);                   // not due yet: count it down,
		ppc_stw(6, 5, 0);
		ppc_jump(s_stub_dispatch);                 // and take the plain dispatcher
		patch_bc(to_c, emit_ptr);
		ppc_mr(4, R_BUD);
		ppc_call((void*)&jit_icmiss_c);
		ppc_cmpli(0, 3, 0, 0);
		e_bc_to(BO_TRUE, BI_CR0_EQ, (u32*)s_stub_exit);
		ppc_mtctr(3);
		ppc_bctr();
	}

	s_code_blocks = emit_ptr;
	emit_ptr = saved_emit_ptr;
	make_address_range_executable(s_code_base, (u32)((u8*)s_code_blocks - (u8*)s_code_base));
}

static void jit_flush(bool restub)
{
	if (s_table_foreign)
	{
		memset(s_entries, 0, (s_entry_mask + 1) * sizeof(void*));
		s_table_foreign = false;
	}
	else if (s_dirty_lo <= s_dirty_hi)
		memset(&s_entries[s_dirty_lo], 0, (s_dirty_hi - s_dirty_lo + 1) * sizeof(void*));
	s_dirty_lo = 0xFFFFFFFF;
	s_dirty_hi = 0;
	if (restub)
		emit_stubs();
	s_code_cur = s_code_blocks;
}

// ── Condition guard (COND_UOP) ───────────────────────────────────────────────
// Returns the branch taken when the condition FAILS.
static u32* e_cond(u32 cond, u32 nz_reg)
{
	if (nz_reg)
	{
		// N/Z still live as the producer's result: N = sign, Z = (result == 0).
		switch (cond)
		{
		case 0x0: ppc_cmpi(0, nz_reg, 0, 0); return e_bc_placeholder(BO_FALSE, BI_CR0_EQ); // EQ
		case 0x1: ppc_cmpi(0, nz_reg, 0, 0); return e_bc_placeholder(BO_TRUE,  BI_CR0_EQ); // NE
		case 0x4: ppc_cmpi(0, nz_reg, 0, 0); return e_bc_placeholder(BO_FALSE, BI_CR0_LT); // MI
		case 0x5: ppc_cmpi(0, nz_reg, 0, 0); return e_bc_placeholder(BO_TRUE,  BI_CR0_LT); // PL
		default:  break;
		}
	}

	switch (cond)
	{
	case 0x0: e_load_byte(3, &Z_FLAG); ppc_cmpi(0, 3, 0, 0); return e_bc_placeholder(BO_TRUE,  BI_CR0_EQ); // EQ
	case 0x1: e_load_byte(3, &Z_FLAG); ppc_cmpi(0, 3, 0, 0); return e_bc_placeholder(BO_FALSE, BI_CR0_EQ); // NE
	case 0x2: e_load_byte(3, &C_FLAG); ppc_cmpi(0, 3, 0, 0); return e_bc_placeholder(BO_TRUE,  BI_CR0_EQ); // CS
	case 0x3: e_load_byte(3, &C_FLAG); ppc_cmpi(0, 3, 0, 0); return e_bc_placeholder(BO_FALSE, BI_CR0_EQ); // CC
	case 0x4: e_load_byte(3, &N_FLAG); ppc_cmpi(0, 3, 0, 0); return e_bc_placeholder(BO_TRUE,  BI_CR0_EQ); // MI
	case 0x5: e_load_byte(3, &N_FLAG); ppc_cmpi(0, 3, 0, 0); return e_bc_placeholder(BO_FALSE, BI_CR0_EQ); // PL
	case 0x6: e_load_byte(3, &V_FLAG); ppc_cmpi(0, 3, 0, 0); return e_bc_placeholder(BO_TRUE,  BI_CR0_EQ); // VS
	case 0x7: e_load_byte(3, &V_FLAG); ppc_cmpi(0, 3, 0, 0); return e_bc_placeholder(BO_FALSE, BI_CR0_EQ); // VC
	case 0x8:   // HI: C && !Z
	case 0x9:   // LS: !C || Z
		e_load_byte(3, &C_FLAG);
		e_load_byte(4, &Z_FLAG);
		ppc_andcx(3, 3, 4, 1);
		return e_bc_placeholder(cond == 0x8 ? BO_TRUE : BO_FALSE, BI_CR0_EQ);
	case 0xA:   // GE: N == V
	case 0xB:   // LT: N != V
		e_load_byte(3, &N_FLAG);
		e_load_byte(4, &V_FLAG);
		ppc_xorx(3, 3, 4, 1);
		return e_bc_placeholder(cond == 0xA ? BO_FALSE : BO_TRUE, BI_CR0_EQ);
	case 0xC:   // GT: !Z && N == V
	case 0xD:   // LE: Z || N != V
		e_load_byte(3, &N_FLAG);
		e_load_byte(4, &V_FLAG);
		ppc_xorx(3, 3, 4, 0);
		e_load_byte(4, &Z_FLAG);
		ppc_orx(3, 3, 4, 1);
		return e_bc_placeholder(cond == 0xC ? BO_FALSE : BO_TRUE, BI_CR0_EQ);
	default:    // NV: never executes
		return e_bc_placeholder(BO_ALWAYS, BI_CR0_EQ);
	}
}

// ── Shifter, immediate amount (lbl_sh_/lbl_shc_ lsli/lsri/asri/rori) ─────────
// v in r4 -> value r5; carry r6 (and reg[R_COUT]) when want_carry.
static void e_shift_imm(u32 shtype, u32 s, bool want_carry)
{
	switch (shtype)
	{
	case 0:   // LSL (s >= 1: LSL #0 is the plain-Rm form)
		if (s)
		{
			if (want_carry) e_rlwinm(6, 4, s, 31, 31);
			e_rlwinm(5, 4, s, 0, 31 - s);
		}
		else
			ppc_mr(5, 4);
		break;

	case 1:   // LSR
		if (s)
		{
			if (want_carry) e_rlwinm(6, 4, 33 - s, 31, 31);
			e_rlwinm(5, 4, 32 - s, s, 31);
		}
		else  // LSR #32
		{
			if (want_carry) e_rlwinm(6, 4, 1, 31, 31);
			ppc_li(5, 0);
		}
		break;

	case 2:   // ASR
		if (s)
		{
			if (want_carry) e_rlwinm(6, 4, 33 - s, 31, 31);
			ppc_srawix(5, 4, s, 0);
		}
		else  // ASR #32
		{
			if (want_carry) e_rlwinm(6, 4, 1, 31, 31);
			ppc_srawix(5, 4, 31, 0);
		}
		break;

	default:  // ROR / RRX
		if (s)
		{
			if (want_carry) e_rlwinm(6, 4, 33 - s, 31, 31);
			e_rlwinm(5, 4, 32 - s, 0, 31);
		}
		else
		{
			e_load_byte(8, &C_FLAG);
			if (want_carry) e_rlwinm(6, 4, 0, 31, 31);
			e_rlwinm(5, 4, 31, 1, 31);
			e_rlwinm(8, 8, 31, 0, 0);
			ppc_orx(5, 5, 8, 0);
		}
		break;
	}

	if (want_carry)
		ppc_stw(6, R_REG, R_COUT * 4);
}

// ── Data processing (lbl_dp_*) ───────────────────────────────────────────────
static bool dp_is_logical(u32 op4)
{
	return op4 == 0x0 || op4 == 0x1 || op4 == 0x8 || op4 == 0x9 ||
	       op4 == 0xC || op4 == 0xD || op4 == 0xE || op4 == 0xF;
}

enum { CARRY_KEEP, CARRY_CONST0, CARRY_CONST1, CARRY_R6 };

static void emit_dp(u32 pc, u32 op, bool& last)
{
	u32 op4 = (op >> 21) & 0xF;
	u32 S   = (op >> 20) & 1;
	u32 rd  = (op >> 12) & 0xF;
	u32 rn  = (op >> 16) & 0xF;
	u32 rm  = op & 0xF;

	bool writes_rd = !(op4 >= 0x8 && op4 <= 0xB);
	bool pcwrite   = writes_rd && rd == 15;
	bool logicalS  = S && dp_is_logical(op4);
	u32  carry     = CARRY_KEEP;

	if (op & 0x02000000)
	{
		// immediate operand2 (_imm0 / _immn / _pc_imm)
		u32 imm8 = op & 0xFF;
		u32 rot  = ((op >> 8) & 0xF) * 2;
		u32 imm  = rot ? ((imm8 >> rot) | (imm8 << (32 - rot))) : imm8;
		if (rn == 15 || pcwrite)
			e_set_pc15(pc + 8);
		ppc_li(5, imm);
		if (logicalS && !pcwrite && rot)
			carry = (imm & 0x80000000) ? CARRY_CONST1 : CARRY_CONST0;
	}
	else
	{
		u32 shtype = (op >> 5) & 3;
		u32 byreg  = (op >> 4) & 1;
		u32 samt   = (op >> 7) & 0x1F;

		if (!byreg && shtype == 0 && samt == 0)
		{
			// plain Rm: one op uop, pcr if either operand reads r15
			if (rn == 15 || rm == 15 || pcwrite)
				e_set_pc15(pc + 8);
			e_load_reg(5, rm);
		}
		else
		{
			// shift uop (shc_ for logical-S ops, sh_ otherwise) then op uop
			bool carry_uop = logicalS;
			if (!byreg)
			{
				if (rm == 15)
					e_set_pc15(pc + 8);
				e_load_reg(4, rm);
				e_shift_imm(shtype, samt, carry_uop);
			}
			else
			{
				if (rm == 15)
					e_set_pc15(pc + 12);   // extra pipeline stage for the Rs fetch
				ppc_li(3, rm);
				ppc_li(4, (op >> 8) & 0xF);
				ppc_li(5, shtype | (carry_uop ? 4 : 0));
				bool known = s_pc15_known; u32 val = s_pc15_val;
				ppc_call((void*)&jit_shift_reg);        // does not touch reg[15]
				s_pc15_known = known; s_pc15_val = val;
				ppc_mr(5, 3);
				if (carry_uop)
				{
					ppc_lwz(6, R_REG, R_COUT * 4);   // "reg[R_COUT].I != 0"
					ppc_negx(8, 6, 0, 0);
					ppc_orx(8, 8, 6, 0);
					e_rlwinm(6, 8, 1, 31, 31);
				}
			}
			if (rn == 15 || pcwrite)
				e_set_pc15(pc + 8);
			if (logicalS && !pcwrite)
				carry = CARRY_R6;
		}
	}

	bool uses_base = !(op4 == 0xD || op4 == 0xF);
	if (uses_base)
		e_load_reg(3, rn);

	if (op4 == 0x5 || op4 == 0x6 || op4 == 0x7)
		e_ca_from_c();

	// r3 = base, r5 = operand2 -> r7 = result
	switch (op4)
	{
	case 0x0: ppc_andx(7, 3, 5, 0); break;                                   // AND
	case 0x1: ppc_xorx(7, 3, 5, 0); break;                                   // EOR
	case 0x2: if (S) ppc_subfcx(7, 5, 3, 0, 0); else ppc_subfx(7, 5, 3, 0, 0); break; // SUB
	case 0x3: if (S) ppc_subfcx(7, 3, 5, 0, 0); else ppc_subfx(7, 3, 5, 0, 0); break; // RSB
	case 0x4: if (S) ppc_addcx(7, 3, 5, 0, 0);  else ppc_addx(7, 3, 5, 0, 0);  break; // ADD
	case 0x5: ppc_addex(7, 3, 5, 0, 0); break;                               // ADC
	case 0x6: ppc_subfex(7, 5, 3, 0, 0); break;                              // SBC
	case 0x7: ppc_subfex(7, 3, 5, 0, 0); break;                              // RSC
	case 0x8: ppc_andx(7, 3, 5, 0); break;                                   // TST
	case 0x9: ppc_xorx(7, 3, 5, 0); break;                                   // TEQ
	case 0xA: ppc_subfcx(7, 5, 3, 0, 0); break;                              // CMP
	case 0xB: ppc_addcx(7, 3, 5, 0, 0); break;                               // CMN
	case 0xC: ppc_orx(7, 3, 5, 0); break;                                    // ORR
	case 0xD: ppc_mr(7, 5); break;                                           // MOV
	case 0xE: ppc_andcx(7, 3, 5, 0); break;                                  // BIC
	default:  ppc_norx(7, 5, 5, 0); break;                                   // MVN
	}

	if (S)
	{
		bool arith = !dp_is_logical(op4);
		if (arith)
		{
			e_flag_c_from_ca();
			// V: ADD-type ((a^r)&(b^r)), SUB-type a-b ((a^b)&(a^r))
			if (op4 == 0x4 || op4 == 0x5 || op4 == 0xB)
			{
				ppc_xorx(9, 3, 7, 0);
				ppc_xorx(10, 5, 7, 0);
			}
			else if (op4 == 0x3 || op4 == 0x7)          // RSB/RSC: a = operand2
			{
				ppc_xorx(9, 5, 3, 0);
				ppc_xorx(10, 5, 7, 0);
			}
			else                                          // SUB/SBC/CMP: a = base
			{
				ppc_xorx(9, 3, 5, 0);
				ppc_xorx(10, 3, 7, 0);
			}
			ppc_andx(9, 9, 10, 0);
			e_rlwinm(9, 9, 1, 31, 31);
			e_store_byte(9, &V_FLAG);
		}
		else if (carry == CARRY_CONST0 || carry == CARRY_CONST1)
		{
			ppc_li(9, carry == CARRY_CONST1 ? 1 : 0);
			e_store_byte(9, &C_FLAG);
		}
		else if (carry == CARRY_R6)
		{
			e_store_byte(6, &C_FLAG);
		}
		e_flags_nz(7);
	}

	if (writes_rd)
		e_store_reg(7, rd);

	if (pcwrite)
	{
		if (S)
		{
			e_ticks(1);
			ppc_mr(R_ADDR, 7);
			e_call((void*)&jit_dp_switchmode);
			e_rlwinm(3, R_ADDR, 0, 0, 29);
		}
		else
			e_rlwinm(3, 7, 0, 0, 29);
		// MOV pc,Rm (returns, calls through a register) and SUB(S) pc,Rn,#n
		// (exception returns) usually go back to one place per site; anything
		// computed from pc or shifted is a jump table and would only thrash.
		bool plain_rm = !(op & 0x02000000) && ((op >> 4) & 0xFF) == 0;
		e_dyn_exit((op4 == 0xD && plain_rm)                          ? ARMC_DYN_MOV :
		           (op4 == 0x2 && (op & 0x02000000) && rn != 15)    ? ARMC_DYN_SUB : ARMC_DYN_DP_OTHER);
		last = true;
	}
}

// ── MUL / MLA (lbl_mul / lbl_mla) ────────────────────────────────────────────
static void emit_mul(u32 op)
{
	u32 rd  = (op >> 16) & 0xF;
	u32 rs  = (op >> 8) & 0xF;
	u32 rm  = op & 0xF;
	u32 rn  = (op >> 12) & 0xF;
	bool S  = (op >> 20) & 1;
	bool mla = (op & 0x00200000) != 0;

	e_load_reg(4, rs);
	e_load_reg(5, rm);
	ppc_mullwx(7, 5, 4, 0, 0);
	if (mla)
	{
		e_load_reg(6, rn);
		ppc_addx(7, 7, 6, 0, 0);
	}
	e_store_reg(7, rd);
	if (S)
		e_flags_nz(7);

	// ticks: t = rs ^ sign(rs); +2 (<=0xFF) / +3 / +4 / +5, MLA one more.
	// (t | 1) keeps cntlzw <= 31 so t == 0 lands in the +2 bucket.
	ppc_srawix(8, 4, 31, 0);
	ppc_xorx(8, 4, 8, 0);
	ppc_ori(8, 8, 1);
	ppc_cntlzwx(8, 8, 0);
	e_rlwinm(8, 8, 29, 3, 31);
	ppc_subfic(8, 8, mla ? 6 : 5);
	ppc_subfx(R_BUD, 8, R_BUD, 0, 0);
}

// ── Memory access fast paths ─────────────────────────────────────────────────
// address in R_ADDR. Read -> r3. Write value in R_VAL.
static void e_mem_read(u32 size)
{
	e_rlwinm(4, R_ADDR, 0, 8, 31);                    // addr & 0xFFFFFF
	if (size == 4)
		ppc_rlwinmx(0, 4, 0, 30, 8, 1);                // & 0xFF800003: MMIO or unaligned
	else
		ppc_rlwinmx(0, 4, 0, 8, 8, 1);                 // & 0x00800000: MMIO
	u32* site = e_bc_placeholder(BO_FALSE, BI_CR0_EQ);
	if (size == 1)
		ppc_xori(4, 4, 3);
	e_rlwinm(4, 4, 0, 11, 31);                        // & ARAM_MASK
	if (size == 4)
		ppc_lwzx(3, R_RAM, 4);
	else
		ppc_lbzx(3, R_RAM, 4);
	cold_push(CK_RD, site, 0, emit_ptr, size);
}

static void e_mem_write(u32 size)
{
	e_rlwinm(4, R_ADDR, 0, 8, 31);
	if (size == 4)
		ppc_rlwinmx(0, 4, 0, 30, 8, 1);
	else
		ppc_rlwinmx(0, 4, 0, 8, 8, 1);
	u32* site = e_bc_placeholder(BO_FALSE, BI_CR0_EQ);
	if (size == 1)
		ppc_xori(4, 4, 3);
	e_rlwinm(4, 4, 0, 11, 31);
	if (size == 4)
		ppc_stwx(R_VAL, R_RAM, 4);
	else
		ppc_stbx(R_VAL, R_RAM, 4);
	cold_push(CK_WR, site, 0, emit_ptr, size);
}

// ── LDR / STR / LDRB / STRB (lbl_mem_*) ──────────────────────────────────────
static void emit_mem(u32 pc, u32 op, bool& last)
{
	bool L = (op >> 20) & 1;
	bool W = (op >> 21) & 1;
	bool B = (op >> 22) & 1;
	bool U = (op >> 23) & 1;
	bool P = (op >> 24) & 1;
	bool I = (op >> 25) & 1;
	u32 rd = (op >> 12) & 0xF;
	u32 rn = (op >> 16) & 0xF;
	u32 rm = op & 0xF;

	bool pcr = I ? (rn == 15 || rm == 15) : (rn == 15);
	if (pcr)
		e_set_pc15(pc + 8);

	// offset
	if (I)
	{
		u32 sh = (op >> 5) & 3;
		u32 sa = (op >> 7) & 0x1F;
		e_load_reg(4, rm);
		switch (sh)
		{
		case 0: if (sa) e_rlwinm(5, 4, sa, 0, 31 - sa); else ppc_mr(5, 4); break;
		case 1: if (sa) e_rlwinm(5, 4, 32 - sa, sa, 31); else ppc_li(5, 0); break;
		case 2: ppc_srawix(5, 4, sa ? sa : 31, 0); break;
		default:
			if (sa)
				e_rlwinm(5, 4, 32 - sa, 0, 31);
			else
			{
				e_load_byte(8, &C_FLAG);
				e_rlwinm(5, 4, 31, 1, 31);
				e_rlwinm(8, 8, 31, 0, 0);
				ppc_orx(5, 5, 8, 0);
			}
			break;
		}
	}

	e_load_reg(3, rn);

	// R_WB = rn +- offset; R_ADDR = pre ? R_WB : rn
	if (!I)
	{
		s32 off = (s32)(op & 0xFFF);
		ppc_addi(R_WB, 3, (u32)(U ? off : -off));
	}
	else if (U)
		ppc_addx(R_WB, 3, 5, 0, 0);
	else
		ppc_subfx(R_WB, 5, 3, 0, 0);
	ppc_mr(R_ADDR, P ? R_WB : 3);

	if (L)
	{
		e_mem_read(B ? 1 : 4);
		if (rd != rn && (!P || W))
			e_store_reg(R_WB, rn);
		e_store_reg(3, rd);
		e_ticks(4);
		if (rd == 15)
		{
			e_ticks(2);
			e_rlwinm(3, 3, 0, 0, 29);
			e_dyn_exit(I ? ARMC_DYN_LDR_REG :      // LDR pc,[pc,rX,lsl #2]: jump table
			           rn == 15 ? ARMC_DYN_LDR_LIT : ARMC_DYN_LDR_IMM);
			last = true;
		}
	}
	else
	{
		if (P && W)
			e_store_reg(R_WB, rn);
		if (P && W && rd == rn)
			ppc_mr(R_VAL, R_WB);
		else
			e_load_reg(R_VAL, rd);
		e_mem_write(B ? 1 : 4);
		if (!P)
			e_store_reg(R_WB, rn);
		e_ticks(3);
	}
}

// ── LDM / STM (lbl_ldm / lbl_stm -> arm_cached_ldm / arm_cached_stm) ─────────
// arm7_jit >= 4 inlines the common case: S clear, non-empty list, base not r15,
// and every word inside one 2 MB ARAM mirror below the AICA registers (a stack
// push/pop). Anything else leaves through a cold stub to the same C helper.
// The helpers charge 2 + 2 per word (+1 for a loaded pc) whatever the address
// (CPUUpdateTicksAccess32 is 1 on this core), so both paths share one constant
// charge after the join.
static void emit_block(u32 pc, u32 op, bool& last)
{
	bool load  = (op >> 20) & 1;
	bool W     = (op >> 21) & 1;
	bool S     = (op >> 22) & 1;
	bool U     = (op >> 23) & 1;
	bool P     = (op >> 24) & 1;
	u32  base  = (op >> 16) & 0xF;
	u32  list  = op & 0xFFFF;
	bool hasPC = load && (list & 0x8000) != 0;
	u32  n     = (u32)__builtin_popcount(list);

	e_set_pc15(pc + 8);

	if (!s_inline_blk || S || n == 0 || base == 15)
	{
		ppc_li(3, op);
		e_call(!load ? (void*)&jit_stm : hasPC ? (void*)&jit_ldm_pc : (void*)&jit_ldm_nopc);
		ppc_subfx(R_BUD, 3, R_BUD, 0, 0);
		if (hasPC)
		{
			u32 lo = ppc_addr_high(3, &arm_ArmNextPC);
			ppc_lwz(3, 3, lo);
			e_dyn_exit(ARMC_DYN_LDM);
			last = true;
		}
		return;
	}

	// arm_blockBase: rn & ~3, first word and writeback value from the count.
	s32 words     = (s32)(4 * n);
	s32 first_off = U ? (P ? 4 : 0) : (P ? 0 : 4) - words;
	s32 wb_off    = U ? words : -words;

	ppc_lwz(3, R_REG, base * 4);
	e_rlwinm(3, 3, 0, 0, 29);
	ppc_addi(R_WB, 3, (u32)wb_off);
	ppc_addi(5, 3, (u32)first_off);
	e_rlwinm(4, 5, 0, 11, 31);                 // ARAM index of the first word
	ppc_addi(6, 4, (u32)(words - 1));          // ...of the last byte
	e_rlwinm(0, 5, 0, 8, 8);                   // bit 23 set: AICA registers
	ppc_orx(6, 6, 0, 0);
	ppc_rlwinmx(0, 6, 0, 0, 10, 1);            // past the 2 MB mirror, or registers
	u32* slow = e_bc_placeholder(BO_FALSE, BI_CR0_EQ);
	ppc_addx(4, 4, R_RAM, 0, 0);
	e_count(ARMC_BLK_INLINE);

	u32 lowest = (u32)__builtin_ctz(list);
	u32 k = 0;
	if (!load)
	{
		for (u32 i = 0; i < 16; i++)
		{
			if (!(list & (1u << i)))
				continue;
			if (i == 15)
				ppc_li(12, pc + 12);           // reg[15] + 4, reg[15] = pc + 8
			else if (i == base && W && i != lowest)
				ppc_mr(12, R_WB);              // written back after the first word
			else
				ppc_lwz(12, R_REG, i * 4);
			ppc_stw(12, 4, 4 * k++);
		}
		if (W)
			e_store_reg(R_WB, base);
	}
	else
	{
		for (u32 i = 0; i < 15; i++)
		{
			if (!(list & (1u << i)))
				continue;
			ppc_lwz(12, 4, 4 * k++);
			e_store_reg(12, i);
		}
		if (W && !(list & (1u << base)))
			e_store_reg(R_WB, base);
		if (hasPC)
		{
			ppc_lwz(3, 4, 4 * k);
			e_rlwinm(3, 3, 0, 0, 29);           // armNextPC = reg[15] & ~3
			u32 lo = ppc_addr_high(12, &arm_ArmNextPC);
			ppc_stw(3, 12, lo);
			ppc_addi(12, 3, 4);                 // reg[15] = armNextPC + 4
			e_store_reg(12, 15);
		}
	}

	cold_push(CK_BLOCK, slow, op, emit_ptr, !load ? 0 : hasPC ? 2 : 1);
	e_ticks(2 + 2 * n + (hasPC ? 1 : 0));
	s_pc15_known = false;                       // the C path may have written it

	if (hasPC)
	{
		e_dyn_exit(ARMC_DYN_LDM);               // r3 = target on both paths
		last = true;
	}
}

// ── One instruction ──────────────────────────────────────────────────────────
static void emit_insn(u32 block_pc, u32 pc, u32 op, bool& last, bool& blockSafe)
{
	s_pc15_known = false;
	u32 nz_fwd = s_nz_fwd_next;
	s_nz_fwd_next = 0;
	s_nz_in_r7 = false;

	// ADVANCE()/DISPATCH(): budget check, then +6
	if (s_fold)
	{
		if (!s_cr0_budget)
			ppc_cmpi(0, R_BUD, 0, 0);          // block start: no charge to test yet
		s_cr0_budget = false;
		cold_push(CK_BUDGET, e_bc_placeholder(BO_FALSE, BI_CR0_GT), pc, 0, 0);
		verify(s_ticks == 0);
		s_ticks = 6;
	}
	else
	{
		ppc_cmpi(0, R_BUD, 0, 0);
		cold_push(CK_BUDGET, e_bc_placeholder(BO_FALSE, BI_CR0_GT), pc, 0, 0);
		e_ticks(6);
	}

	u32 cond = op >> 28;
	u32* fail_site = (cond != 0xE) ? e_cond(cond, nz_fwd) : 0;

	u32 fam = (op >> 26) & 3;
	if (fam == 1)
	{
		emit_mem(pc, op, last);
		if (!((op >> 20) & 1))
			blockSafe = false;
	}
	else if (fam == 0)
	{
		bool isMulSpace = (op & 0x0FC000F0) == 0x00000090;
		bool isSwp      = (op & 0x0FB00FF0) == 0x01000090;
		bool isMrsMsr   = (((op >> 23) & 3) == 2) && (((op >> 20) & 1) == 0) && !isMulSpace && !isSwp;

		if (isMulSpace)
			emit_mul(op);
		else if (isSwp)
		{
			ppc_li(3, op);
			e_call((void*)&jit_swp);
			e_ticks(4);
			blockSafe = false;
		}
		else if (isMrsMsr)
		{
			bool toPSR = (op >> 21) & 1;
			bool spsr  = (op >> 22) & 1;
			u32  rd    = (op >> 12) & 0xF;
			if (!toPSR)
			{
				if (!spsr)
					e_call((void*)&CPUUpdateCPSR);
				ppc_lwz(3, R_REG, (spsr ? 17 : 16) * 4);
				e_store_reg(3, rd);
			}
			else
			{
				ppc_li(3, op);
				e_call(spsr ? (void*)&jit_msr_spsr : (void*)&jit_msr_cpsr);
				blockSafe = false;
			}
			e_ticks(1);
		}
		else
			emit_dp(pc, op, last);
	}
	else if (fam == 2)
	{
		if (!((op >> 25) & 1))
		{
			emit_block(pc, op, last);
			blockSafe = false;
		}
		else
		{
			s32 offset = op & 0x00FFFFFF;
			if (offset & 0x00800000)
				offset |= 0xFF000000;
			offset <<= 2;
			u32 target = pc + 8 + (u32)offset;

			if (op & 0x01000000)
			{
				ppc_li(3, pc + 4);
				e_store_reg(3, 14);
				e_ticks(3);
			}
			else
			{
				bool selfLoop = blockSafe && target >= block_pc && target <= pc;
				e_ticks(selfLoop ? 103 : 3);
			}
			e_link(target);
			last = true;
		}
	}
	else
	{
		if (((op >> 24) & 0xF) == 0xF)
		{
			e_ticks(3);
			e_set_pc15(pc + 8);
			ppc_li(3, op);
			e_call((void*)&jit_swi);
		}
		else
		{
			e_set_pc15(pc + 8);
			ppc_li(3, op);
			ppc_li(4, pc);
			e_call((void*)&jit_undefined);
		}
		u32 lo = ppc_addr_high(3, &arm_ArmNextPC);
		ppc_lwz(3, 3, lo);
		e_dyn_exit(ARMC_DYN_SWI);
		last = true;
	}

	if (fail_site)
		cold_push(last ? CK_FAIL_LAST : CK_FAIL, fail_site, pc + 4, 0, 0);

	if (s_fold)
	{
		if (last)
		{
			verify(s_ticks == 0);              // charged before the exit branch
		}
		else
		{
			e_charge(true);
			s_cr0_budget = true;
			// Forward N/Z only from an unconditional producer: a failed
			// condition would reach the next instruction with r7 unset.
			if (s_nz_in_r7 && cond == 0xE)
				s_nz_fwd_next = 7;
		}
	}
}

// The next instruction's code starts here: resolve fail-continue targets.
static void mark_insn_start()
{
	u32* start = emit_ptr;
	for (u32 i = 0; i < s_pending_n; i++)
		patch_bc(s_pending_back[i], start);
	s_pending_n = 0;
	for (u32 i = 0; i < s_cold_n; i++)
		if (s_cold[i].kind == CK_FAIL && !s_cold[i].back)
			s_cold[i].back = start;
}

// ── Block compiler ───────────────────────────────────────────────────────────
static void* compile_block(u32 block_pc)
{
	if ((u32)((s_code_base + s_code_words) - s_code_cur) < MAX_BLOCK_WORDS)
	{
		printf("[ARM7JIT] code cache full after %u blocks, flushing\n", s_blocks);
		s_flushes++;
		jit_flush(false);
	}

	u32* start = s_code_cur;
	u32* saved_emit_ptr = emit_ptr;
	emit_ptr = start;

	// Link entry (used by patched static exits): DISPATCH()'s FIQ sample. No
	// FIQ -> skip the two data words into the code, whose instruction 0 does
	// the budget check. The dispatcher already sampled FIQ and enters at code.
	e_load_byte(3, &armFiqEnable);
	e_load_byte(4, &e68k_out);
	ppc_andx(3, 3, 4, 1);
	u32* no_fiq = e_bc_placeholder(BO_TRUE, BI_CR0_EQ);
	ppc_li(3, block_pc);
	ppc_jump(s_stub_dispatch);
	u32* len_word = emit_ptr;
	ppc_emit(0);            // code[-4]: entries since the last census dump (census only)
	ppc_emit(0);            // code[-3]: ARM instructions in the block
	ppc_emit(0);            // code[-2]: words from the link entry to code
	ppc_emit(block_pc);     // code[-1]: ARM pc, checked by jit_lookup
	void* code = emit_ptr;
	patch_bc(no_fiq, (u32*)code);
	len_word[2] = (u32)((u32*)code - start);

	s_cold_n = 0;
	s_pending_n = 0;
	s_ticks = 0;
	s_cr0_budget = false;
	s_nz_fwd_next = 0;
	ARMC(ARMC_COMPILE);
	if (s_census)
	{
		// Per-block entry count, for the [ARMHOT] list and the totals.
		u32 lo = ppc_addr_high(12, len_word);
		ppc_lwz(11, 12, lo);
		ppc_addi(11, 11, 1);
		ppc_stw(11, 12, lo);
	}

	bool last = false;
	bool blockSafe = true;
	u32  pc = block_pc;
	u32  n = 0;

	for (;;)
	{
		mark_insn_start();
		u32 op = arm_ReadMem32(pc & ARAM_MASK);
		emit_insn(block_pc, pc, op, last, blockSafe);
		pc += 4;
		if (last)
			break;

		if (++n >= MAX_BLOCK_INSNS)
		{
			// lbl_rehome: re-dispatch at the next instruction
			mark_insn_start();
			e_link(pc);
			break;
		}

		if ((n % COLD_FLUSH_INSNS) == 0)
			flush_cold();
	}

	flush_cold();
	verify(s_pending_n == 0);
	len_word[1] = (pc - block_pc) >> 2;

	u32* end = emit_ptr;
	emit_ptr = saved_emit_ptr;
	verify((u32)(end - start) < MAX_BLOCK_WORDS);

	make_address_range_executable(start, (u32)((u8*)end - (u8*)start));
	s_code_cur = end;
	u32 idx = (block_pc >> 2) & s_entry_mask;
	s_entries[idx] = code;
	if (idx < s_dirty_lo) s_dirty_lo = idx;
	if (idx > s_dirty_hi) s_dirty_hi = idx;
	s_blocks++;
	return code;
}

// ── Engine control ───────────────────────────────────────────────────────────
static bool jit_setup()
{
	if (s_setup_done)
		return s_setup_ok;
	s_setup_done = true;

	u8* code; u32 code_bytes; void** entries; u32 entry_count;
	arm7_cached_borrow_buffers(&code, &code_bytes, &entries, &entry_count);

	if ((size_t)code & 3)
	{
		u32 skip = 4 - ((size_t)code & 3);
		code += skip;
		code_bytes -= skip;
	}
	if ((entry_count & (entry_count - 1)) != 0 || code_bytes < 4 * MAX_BLOCK_WORDS * 4)
	{
		printf("[ARM7JIT] unusable buffers (code %u B, table %u), JIT disabled\n", code_bytes, entry_count);
		return false;
	}

	s_code_base  = (u32*)code;
	s_code_words = code_bytes / 4;
	s_entries    = entries;
	s_entry_mask = entry_count - 1;
	s_setup_ok   = true;
	return true;
}

void arm_jit_on_reset()
{
	s_active = get_arm7_jit_preset() && !s_failed && jit_setup();
	if (!s_active)
	{
		s_table_foreign = true;   // the cached interpreter owns the table now
		return;
	}
	s_link     = get_arm7_jit_preset() >= 2;
	s_retcache = get_arm7_jit_preset() >= 3;
	s_inline_blk = get_arm7_jit_preset() >= 4;
	s_fold     = get_arm7_jit_preset() >= 5;
	s_census   = g_jit_ccalls_preset != 0;

	jit_flush(true);
	if (!s_announced)
	{
		s_announced = true;
		printf("[ARM7JIT] engine: JIT (code %u KB, %u blocks max table)\n",
		       (s_code_words * 4) / 1024, s_entry_mask + 1);
	}
}

bool arm_jit_active()
{
	return s_active;
}

void arm_jit_run(u32 CycleCount)
{
	s_slices++;
	ARMC(ARMC_SLICE);
	((void (*)(s32))s_stub_entry)((s32)CycleCount);
}

// Once a second from the SPG stats block, next to the jit_ccalls [CC] dump.
void arm_jit_census_dump(double seconds)
{
	if (!s_census || !s_active || seconds <= 0.0)
		return;

	u32 c[ARMC_COUNT];
	memcpy(c, s_cnt, sizeof(c));
	memset(s_cnt, 0, sizeof(s_cnt));
	u64 t[ARMT_COUNT];
	memcpy(t, s_tcost, sizeof(t));
	memset(s_tcost, 0, sizeof(s_tcost));
	#define PER_S(i) ((double)c[i] / seconds)
	#define WALL(i)  ((double)ticks_to_microsecs(t[i]) / 1e6 / seconds * 100.0)

	// Walk the compiled blocks (the table's dirty range) for entry counts and
	// the hottest blocks, then clear the counts. Instructions = entries x block
	// length, a slight overcount where a block is left early (budget, FIQ).
	enum { HOT_N = 10 };
	u32* hot[HOT_N] = { 0 };
	u64  entries = 0, insns = 0;
	for (u32 i = s_dirty_lo; i <= s_dirty_hi && s_dirty_lo <= s_dirty_hi; i++)
	{
		u32* code = (u32*)s_entries[i];
		if (!code)
			continue;
		u32 n = code[-4];
		if (!n)
			continue;
		entries += n;
		insns   += (u64)n * code[-3];
		for (u32 k = 0; k < HOT_N; k++)
		{
			if (!hot[k] || n > hot[k][-4])
			{
				for (u32 m = HOT_N - 1; m > k; m--)
					hot[m] = hot[m - 1];
				hot[k] = code;
				break;
			}
		}
	}

	printf("[ARMJIT] level %d  slices %.0f/s  block entries %.0f/s  instructions ~%.0f/s (%.1f per entry)  compiles %.0f/s  fiq %.0f/s\n",
	       get_arm7_jit_preset(), PER_S(ARMC_SLICE), (double)entries / seconds, (double)insns / seconds,
	       entries ? (double)insns / (double)entries : 0.0, PER_S(ARMC_COMPILE), PER_S(ARMC_FIQ));
	for (u32 k = 0; k < HOT_N && hot[k]; k++)
	{
		u32* code = hot[k];
		u32 pc = code[-1], n = code[-3], shown = n < 12 ? n : 12;
		printf("[ARMHOT] %2u pc %08x %7.0f/s x%-3u %4.1f%% of insns:", k + 1, pc,
		       (double)code[-4] / seconds, n, insns ? 100.0 * (double)code[-4] * n / (double)insns : 0.0);
		for (u32 j = 0; j < shown; j++)
			printf(" %08x", arm_ReadMem32((pc + 4 * j) & ARAM_MASK));
		printf(n > shown ? " ...\n" : "\n");
	}
	for (u32 i = s_dirty_lo; i <= s_dirty_hi && s_dirty_lo <= s_dirty_hi; i++)
		if (s_entries[i])
			((u32*)s_entries[i])[-4] = 0;
	printf("[ARMJIT]   wall %% in C: dispatch %.2f  slow read %.2f  slow write %.2f  ldm/stm %.2f  other %.2f  (compare with arm:)\n",
	       WALL(ARMT_DISPATCH), WALL(ARMT_RD), WALL(ARMT_WR), WALL(ARMT_BLOCK), WALL(ARMT_OTHER));
	printf("[ARMJIT]   exits by shape/s: mov pc,Rm %.0f  sub pc,Rn,# %.0f  other dp %.0f  ldr pc,[Rn,#] %.0f  ldr pc,[pc,#] %.0f  ldr pc,[Rn,Rm] %.0f  ldm pc %.0f  swi/undef %.0f\n",
	       PER_S(ARMC_DYN_MOV), PER_S(ARMC_DYN_SUB), PER_S(ARMC_DYN_DP_OTHER), PER_S(ARMC_DYN_LDR_IMM),
	       PER_S(ARMC_DYN_LDR_LIT), PER_S(ARMC_DYN_LDR_REG), PER_S(ARMC_DYN_LDM), PER_S(ARMC_DYN_SWI));
	#undef WALL
	printf("[ARMJIT]   dispatch stub %.0f/s (into C %.0f/s)  static link C %.0f/s\n",
	       PER_S(ARMC_DISPATCH), PER_S(ARMC_DISPATCH_C), PER_S(ARMC_LINK_C));
	printf("[ARMJIT]   dynamic exits %.0f/s  cached sites %.0f/s  hits %.0f/s  misses %.0f/s  repatches %.0f/s  demoted %u\n",
	       PER_S(ARMC_DYN), PER_S(ARMC_IC_SITE),
	       c[ARMC_IC_SITE] >= c[ARMC_IC_MISS] ? (double)(c[ARMC_IC_SITE] - c[ARMC_IC_MISS]) / seconds : 0.0,
	       PER_S(ARMC_IC_MISS), PER_S(ARMC_IC_PATCH), c[ARMC_IC_DEMOTE]);
	printf("[ARMJIT]   C helpers/s: slow read %.0f  slow write %.0f  ldm %.0f  stm %.0f  other %.0f  (ldm/stm inline %.0f/s)\n",
	       PER_S(ARMC_RD_SLOW), PER_S(ARMC_WR_SLOW), PER_S(ARMC_LDM), PER_S(ARMC_STM), PER_S(ARMC_OTHER),
	       PER_S(ARMC_BLK_INLINE));
	#undef PER_S
}

void arm_jit_after_init()
{
	if (s_selftest_started || !get_arm7_jit_preset())
		return;
	s_selftest_started = true;

	if (!jit_setup())
	{
		s_failed = true;
		arm_Reset();
		return;
	}

	// Runs the 45 arm7di conformance binaries through arm_Run(1) with the JIT
	// latched (arm_Reset() inside the harness). Per-instruction budget checks
	// make arm_Run(1) execute exactly one instruction, as the harness expects.
	int failed = arm_RunSelfTests();
	if (failed != 0)
	{
		s_failed = true;
		printf("[ARM7JIT] self-test FAILED (%d) - falling back to the cached interpreter\n", failed);
	}
	else
		printf("[ARM7JIT] self-test PASS\n");

	arm_Reset();   // pristine post-init state, engine re-latched
}

#else   // non-Wii hosts: no PPC JIT

void arm_jit_after_init() {}
void arm_jit_on_reset() {}
bool arm_jit_active() { return false; }
void arm_jit_run(u32) {}
void arm_jit_census_dump(double) {}

#endif
